---
- name: Configure web and database servers
  hosts: all
  become: true
  vars:
    db_host: "{{ db_host }}"
    db_name: "{{ db_name }}"
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"
  roles:
    - { role: server, when: "'server' in group_names" }
    - { role: database, when: "'dadtabase' in group_names" }