---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Install psycopg2
  apt:
    name: python3-psycopg2
    state: present

- name: Create PostgreSQL database
  postgresql_db:
    name: "{{ db_name }}"
    state: present

- name: Create PostgreSQL user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: "ALL"
    state: present
